on:
  release:
    types: [created]

name: Handle Release

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:22.04
        ocaml-compiler:
          - "4.14.1"

    container: ${{ matrix.container }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v3


      - name: Install system packages
        run:  |
          apt-get -yq update && \
          apt-get -y upgrade && \
          apt-get -yq --no-install-suggests --no-install-recommends install \
          ocaml=4.14.1 \
          menhir \
          llvm-14 \
          llvm-14-dev \
          m4 \
          clang-14 \
          git \
          libclang-14-dev \
          ca-certificates \
          pkg-config \
          opam=2.1.4 \
          valgrind \
          make

      - name: Link clang bin
        run: ln -s /usr/bin/clang-14 /usr/bin/clang

      - name: Opam init
        run: opam init --disable-sandboxing

      - name: Install deps
        run: eval $(opam env) && make install

      - name: Build binary
        run: eval $(opam env) && make

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'platypus'